# Generated by Django 3.0.8 on 2020-07-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='secundary_categories',
            new_name='secondary_categories',
        ),
    ]
